### ISSUE TITLE
Warning ack-flag

### ISSUE THREAD

**Issue by raschy** [NemoN/ioBroker.ryd#21]
Version 0.3.3 in /opt/iobroker/node_modules/iobroker.ryd, node: v12.22.5, js-controller: 3.3.15

Wahrscheinlich seit einem letzten Update des js-Controllers gibt der Adapter eine Warnung aus:
'Read-only state "ryd.0.lastUpdate" has been written without ack-flag with value "Sat Sep 18 2021 09:00:12 GMT+0200 (GMT+02:00)'.
Ebenso wird der Type des Datenpunkts angemeckert: 'State value to set for "ryd.0.lastUpdate" has to be type "number" but received type "object"'.

**Comment by 92lleo** [comment]
I guess it's best to move the state creation  https://github.com/NemoN/ioBroker.ryd/blob/780e02f0daccac8dd9d67f18bcc77311ba2e0b45/main.js#L235
into the user states
https://github.com/NemoN/ioBroker.ryd/blob/780e02f0daccac8dd9d67f18bcc77311ba2e0b45/main.js#L129
and check for correct types. I can look into that the next few days

**Comment by NemoN** [comment]
@92lleo " I can look into that the next few days"

would be great 👍

**Comment by raschy** [comment]
bei mir funktioniert folgende Lösung: in main.js in Zeile 171 "object" statt "number" und in Zeile 178 noch ein ", true" hinzufügen.

**Comment by 92lleo** [comment]
> next few days

more like next few weeks, sorry. :D

> in main.js in Zeile 171 "object" statt "number" und in Zeile 178 noch ein ", true"

genau, das ist eigentlich die ganze Magic. Sonst auch gern den verlinkten commit oben auschecken, der sollte auch funktionieren, hab ihn nur noch nicht PR bereit.

**Comment by raschy** [comment]
Danke. Fürs fixen und mergen.
