### ISSUE TITLE
Forced logout from android app

### ISSUE THREAD

**Issue by 92lleo** [NemoN/ioBroker.ryd#7]
Hi @NemoN 
Thanks for the ryd adapter! Works flawlessly for me. 
Have you found the sweet spot for the refresh time setting? within 15-19 minutes seems to be too much, as I get logged out of the ryd android app constantly. The logout only happens when I have the adapter running, so I guess ryd is recognizing "bot behaviour" and ending all sessions, which leads to app logout.

**Comment by NemoN** [comment]
Hello @92lleo 

Good question: I refresh every 60 minutes and have no problems at all. (But I using the Ryd app not much)
Since the adapter is using a version string from a older Ryd app version - It could help to enter the latest version here...

**Comment by 92lleo** [comment]
Hi, thanks for the quick answer. I set my schedule to 60 minutes as well, still have the same issue. I'll try to play around with the version number and phone name/resolution to mimic mine.

**Comment by Ilovegym66** [comment]
Hi, same here, some hints for the setup ? App installed on Samsung S20 with Android 10.

**Comment by 92lleo** [comment]
I updated the version string to the current one `2.52.4(201008000)`, let's see if this helps. 
If not: It seems like you always call the login endpoint to get the auth token. Did you try to reuse the auth token or do you know about it's validity?

**Comment by 92lleo** [comment]
3 days later, no forced logout. seems like updating the version string does the trick

**Comment by NemoN** [comment]
great 👍 i will update the default package with the new version

**Comment by 92lleo** [comment]
Merged and still no issues in the android app. Closing

**Comment by luboganev** [comment]
You guys do realize you're reverse engineering a proprietary API without any authorization from the owner, right?

**Comment by NemoN** [comment]
@luboganev 

Is there a problem with the adapter or the API? 

These and similar requests remained without response: https://support.ryd.one/hc/de-at/community/posts/207656449-Alternativer-Zugriff-via-Web-Schnittstelle-in-Planung-

That is why this adapter was created.

**Comment by luboganev** [comment]
Exactly. There was never a response saying there will be a Web API. There is no public API documentation for the API because it's not a public API. So whatever you coded here is a reverse engineered shot in the dark that has unknown effects. And this issue reported here is a direct effect of these unknown effects.

Besides this there is no problem with this project.
